name: at_daemon_client
description: A starting point for Dart libraries or applications.
version: 1.0.0
# homepage: https://www.example.com

environment:
  sdk: '>=2.17.6 <3.0.0'

dependencies:
  at_daemon_core: ^1.0.0
  async: ^2.9.0

dependency_overrides:
  at_daemon_core:
    path: ../at_daemon_core

dev_dependencies:
  lints: ^1.0.0
  test: ^1.16.0
