# This service can be started on a docker swarm
# NOTE *** Update the location of the certficates ***
# docker stack deploy -c ./at_proxyserver.yml proxyserver
services:
   at_proxyserver:
    image: atsigncompany/at_proxyserver
    command: "proxy0001.atsign.org:443 root.atsign.org:64 1443"
    deploy:
      replicas: 3
      resources:
        limits:
          cpus: '0.25'
          memory: '50M'
        reservations:
          memory: '6M'
    ports:
      - target: 1443
        published: 443
    volumes:
      - "<Location Of Certificates>:/atsign/certs"