name: at_daemon_server
description: A starting point for Dart libraries or applications.
version: 1.0.0
# homepage: https://www.example.com

environment:
  sdk: '>=2.17.6 <3.0.0'

dependencies:
  at_client: ^3.0.30
  at_daemon_core: ^1.0.0
  at_server_spec: ^3.0.9
  shelf: ^1.3.1
  shelf_web_socket: ^1.0.2
  web_socket_channel: ^2.2.0
  async: ^2.9.0
  crypton: ^2.0.5
  json_annotation: ^4.6.0
  at_onboarding_cli: ^1.0.0

dev_dependencies:
  lints: ^1.0.0
  test: ^1.16.0
  build_runner: ^2.2.0
  json_serializable: ^6.3.1

dependency_overrides:
  at_daemon_core:
    path: ../at_daemon_core
  at_commons:
    git:
      url: https://github.com/atsign-foundation/at_tools.git
      path: at_commons
      ref: fix_atKey_fromString_and_toString

