name: at_secondary_proxy
description: A reverse proxy through which clients can connect to secondary servers
version: 1.0.1

environment:
  sdk: '>=2.16.2 <3.0.0'


dependencies:
  at_commons: ^5.4.1
  at_utils: ^3.2.0
  at_lookup: ^3.1.0

dev_dependencies:
  lints: ^6.0.0
  test: ^1.26.3
  mockito: ^5.5.0
  build_runner: ^2.7.0
