name: proxy_rebuild
# Creates a new image for atsigncompany/at_proxyserver whenever updated
# certificates are merged to trunk or if Dockerfile is bumped
on:
  push:
    branches:
      - trunk
    paths:
      - 'packages/at_secondary_proxy/certs/cert.pem'
      - 'packages/at_secondary_proxy/tools/Dockerfile'
  workflow_dispatch:

permissions:  # added using https://github.com/step-security/secure-workflows
  contents: read

jobs:
  at_proxyserver:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write # for creating OIDC tokens for signing.
    outputs:
      digest: ${{ steps.docker_build_proxy.outputs.digest }}
    steps:
      - name: Checkout trunk
        uses: actions/checkout@93cb6efe18208431cddfb8368fd83d5badbf9bfd # v5.0.1
      - name: Install cosign
        uses: sigstore/cosign-installer@faadad0cce49287aee09b3a48701e75088a2c6ad # v4.0.0
      - name: Set up QEMU
        uses: docker/setup-qemu-action@c7c53464625b32c7a7e944ae62b3e17d2b600130 # v3.7.0
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@e468171a9de216ec08956ac3ada2f0791b6bd435 # v3.11.1
      - name: Login to DockerHub
        uses: docker/login-action@5e57cd118135c172c3672efd75eb46360885c0ef # v3.6.0
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@318604b99e75e41977312d83839a89be02ca4893 # v5.9.0
        with:
          tags: |
            type=raw,value=latest
            type=raw,value=gha${{ github.run_number }}
          images: |
            atsigncompany/at_proxyserver
          labels: |
            org.opencontainers.image.description=Atsign Proxy Server
      - name: Build and push at_proxyserver
        id: docker_build_proxy
        uses: docker/build-push-action@263435318d21b8e681c14492fe198d362a7d2c83 # v6.18.0
        with:
          file: packages/at_secondary_proxy/tools/Dockerfile
          push: true
          sbom: true
          provenance: version=v1,mode=max
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          platforms: |
            linux/amd64
            linux/arm64/v8
      - name: Sign the images with GitHub OIDC Token
        env:
          DIGEST: ${{ steps.docker_build_proxy.outputs.digest }}
          TAGS: ${{ steps.meta.outputs.tags }}
        run: |
          images=""
          for tag in ${TAGS}; do
            images+="${tag}@${DIGEST} "
          done
          cosign sign --yes ${images}

  slsa_provenance:
    needs: [at_proxyserver]
    permissions:
      actions: read # for detecting the Github Actions environment.
      id-token: write # for creating OIDC tokens for signing.
      packages: write # for uploading attestations.
    uses: slsa-framework/slsa-github-generator/.github/workflows/generator_container_slsa3.yml@v2.1.0
    with:
      image: "atsigncompany/at_proxyserver"
      digest: ${{ needs.at_proxyserver.outputs.digest }}
    secrets:
      registry-username: ${{ secrets.DOCKERHUB_USERNAME }}
      registry-password: ${{ secrets.DOCKERHUB_TOKEN }}
