name: static_analysis

on:
  push:
    branches:
      - trunk
  pull_request:
    branches:
      - trunk

permissions: # added using https://github.com/step-security/secure-workflows
  contents: read

jobs:
  static_analysis:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
      - uses: dart-lang/setup-dart@e51d8e571e22473a2ddebf0ef8a2123f0ab2c02c # v1.7.1
        with:
          sdk: stable
      - uses: actions/setup-go@d35c59abb061a4a6fb18e82ac0862c26744d6ab5 # v5.5.0
        with:
          go-version: "stable"
          cache-dependency-path: tools/osv-scanner/go.sum

      # Runs dart lint rules
      - name: Install dependencies and run analyze - at_secondary_proxy
        working-directory: packages/at_secondary_proxy
        run: |
          dart pub get
          dart analyze

      - name: Run osv-scanner
        working-directory: packages/at_secondary_proxy
        run: |
          go install github.com/google/osv-scanner/v2/cmd/osv-scanner@04a8728383d8f286cf2b0f110e68482e8773df6e # v2.2.1
          osv-scanner --lockfile=./pubspec.lock
