name: unit_tests

permissions:
  contents: read

on:
  pull_request:
    branches:
      - trunk

jobs:
  unit_tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        package:
          - at_secondary_proxy
        dart:
          - stable
          - beta
    steps:
      - name: Checkout code
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

      - name: Set up Dart SDK
        uses: dart-lang/setup-dart@6afc89df92d6eb3834022f73cd65adc8cdfcb92d # v1.8.1
        with:
          sdk: ${{ matrix.dart}}

      - name: Install dependencies
        working-directory: packages/${{ matrix.package }}
        run: |
          dart pub get

      - name: Run tests
        working-directory: packages/${{ matrix.package }}
        run: |
          dart test
